version: '3.8'

services:
  backend:
    image: registry.gitlab.com/kuzznya/junction-avp-backend:latest
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: admin
      DB_PASSWORD: password
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      SEC_SECRET: 12345678
    ports:
      - '80:8080'
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
