name: Manual deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Docker Registry
        run: >
          echo ${{ secrets.GITLAB_TOKEN }} | docker login --username kuzznya --password-stdin registry.gitlab.com/kuzznya
      - name: Deploy stack
        run: docker stack deploy --compose-file docker-compose.yml --prune --with-registry-auth junction
