name: Main CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build image
        run: >
          ./gradlew jib
          -Djib.to.image='ghcr.io/kuzznya/junction-avp-backend'
          -Djib.to.auth.username=kuzznya
          -Djib.to.auth.password='${{ secrets.GITHUB_TOKEN }}'
          -Djib.console=plain
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare .kube directory
        run: mkdir ~/.kube || echo "Cannot create ~/.kube directory, skipping"
      - name: Prepare kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment backend --namespace junction
