name: Remove stack

on:
  workflow_dispatch:

jobs:
  remove-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup remote Docker connection
        uses: pcjun97/action-setup-docker-host-ssh@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      - name: Remove stack
        run: docker stack rm junction && docker volume rm -f junction_db-data
